field: 23107aa4-4dba-42d1-9478-9147f2d514f2 # Page Content
fieldLayouts:
  ae2ec2d0-71a2-49f6-8bd7-d82cd3e90e32:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3b448104-4da5-4158-962c-62844d19deba # Index Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3adf2c35-8050-457b-9a9f-8dc6a77d48fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b232a58-b0cb-4e89-b2f8-f8bc860646b8
        userCondition: null
fields:
  3b448104-4da5-4158-962c-62844d19deba: # Index Type
    columnSuffix: iygsydbw
    contentColumnType: string
    fieldGroup: null
    handle: indexType
    instructions: null
    name: 'Index Type'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Games
            -
              - value
              - games
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Staff
            -
              - value
              - staff
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Events
            -
              - value
              - events
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blog
            -
              - value
              - blog
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Menu
            -
              - value
              - menu
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: index
name: Index
sortOrder: 4
