fieldLayouts:
  e9696387-23a9-4d03-a6ab-4dc3e47df9d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: da36066a-b20d-4b34-8df0-8d11ab56e51a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7c8c4062-827a-4c4d-a875-f440ddad9ae9 # Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c57fbf4f-f8a0-437b-a657-818bc9b72c9e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 377046e5-7ec5-47a1-b3b4-d8e9ab8903cb # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: effac3bf-27c6-4d3c-8a7b-c85dc78d6fb7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5a700407-6841-41f6-b00d-ea5f93fbe111
            userCondition: null
          -
            elementCondition: null
            fieldUid: 58755d9e-c247-42e4-bdf5-5a87b084261e # Search Keywords
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3abc2880-876b-45f9-bc4a-be51961d517d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2fc72a6-7afb-4312-a039-45db63a8cc16 # Prevent Indexing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 153bf48c-bf45-4514-ac42-097cf77fb0f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5b57cb73-5370-409f-bf47-2d6ab73ea614
        userCondition: null
handle: item
hasTitleField: true
name: Item
section: 0fbedee6-67b3-4fb4-8396-b18f150b191b # Menu
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
