fieldLayouts:
  8d3e2286-6422-4f4e-beb5-1b9204dd9c55:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9704ecdb-7c33-4317-9782-e8cbfe8245bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 377046e5-7ec5-47a1-b3b4-d8e9ab8903cb # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84c981fa-8db5-48c8-9f35-10ca464fae26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a9bea51c-40ef-4367-888c-df2f007a87f8 # Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 379ea050-a07b-4631-97de-5392081fbf97
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 30cf60a4-ec37-4826-883b-3471d8cdd4b6 # Duration
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 701fbccc-92ab-4d7f-a548-cd9dbd8b622c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0337e472-a264-42ab-a0d9-6d97f83a7812
            userCondition: null
          -
            elementCondition: null
            fieldUid: 58755d9e-c247-42e4-bdf5-5a87b084261e # Search Keywords
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8879fa65-b6a1-411d-a7a4-ff773f61084f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2fc72a6-7afb-4312-a039-45db63a8cc16 # Prevent Indexing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6526d420-6a7c-4b71-b94d-67356a79855a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03664ba2-0168-487f-b0f9-ae509391e5c5
        userCondition: null
handle: oneTimeEvent
hasTitleField: true
name: 'One-Time Event'
section: 9006d492-8fc8-4651-b6b9-76d7dd9105df # Events
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
