fieldLayouts:
  61d9ba92-ca27-4bc0-9b5c-97eae5f0514d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ddefccd2-c443-449a-9f2d-f6b2c4e35ca4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 23107aa4-4dba-42d1-9478-9147f2d514f2 # Page Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8a932c7-0684-43cc-add3-9d469c7366b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 58755d9e-c247-42e4-bdf5-5a87b084261e # Search Keywords
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2c6312d-c7c5-4175-9d1f-8270548759cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee2fe222-368d-444e-9c71-c1984c584e46
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4b2498f-ea00-4422-aebc-d74b9a44cead
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 27cbc126-11fd-4160-bdf5-c276e7eb4d9f
        userCondition: null
handle: page
hasTitleField: true
name: Page
section: efadae87-ce47-4df9-9f15-38ce6f2f898c # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
