fieldLayouts:
  0af06b02-5f84-4020-bc4a-4b6cef63e918:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 93d9a730-4362-4928-be87-6d204a259e6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 377046e5-7ec5-47a1-b3b4-d8e9ab8903cb # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eb10f8d-9f7a-42f1-bb12-d1fd7f736725
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b188e87-2539-40c9-aed6-3e8a86250737 # Day of Week
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a663cd68-ad7b-4374-8380-7796c5332a46
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0493a47-0f48-4be1-aff8-55023a1ec8c4 # Start Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c70bcb5f-8093-431f-af75-f3f96ebeb233
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 30cf60a4-ec37-4826-883b-3471d8cdd4b6 # Duration
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a0c0b6f-1cb6-44b0-b519-7258db5645f4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ac61ff9f-41ab-4fd9-9f0f-20673c1746c4
            userCondition: null
          -
            elementCondition: null
            fieldUid: 58755d9e-c247-42e4-bdf5-5a87b084261e # Search Keywords
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2780746-98a6-4ce9-9054-d40edf6299b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2fc72a6-7afb-4312-a039-45db63a8cc16 # Prevent Indexing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75efe9f0-d3f8-45ae-aeef-a8ea32e56db8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40ec2ed4-9810-4c78-b616-88439aa4a381
        userCondition: null
handle: weeklyEvent
hasTitleField: true
name: 'Weekly Event'
section: 9006d492-8fc8-4651-b6b9-76d7dd9105df # Events
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
