fieldLayouts:
  84424a52-f93a-4713-9f88-2b7fad726698:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f0e3ca01-56db-4ef6-b647-6297655baf54
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b3578ab-bf13-4d35-8ccd-ec861eed672d
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
