columnSuffix: wjhikzdg
contentColumnType: string(255)
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: bggLink
instructions: null
name: 'BGG Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
