columnSuffix: null
contentColumnType: string
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: blogImage
instructions: null
name: 'Blog Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:927a5a45-cf0c-49eb-9ca9-0090121e9c8b' # Images
  defaultUploadLocationSubpath: blog
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:927a5a45-cf0c-49eb-9ca9-0090121e9c8b' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:927a5a45-cf0c-49eb-9ca9-0090121e9c8b' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
