columnSuffix: uydejwvo
contentColumnType: text
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: description
instructions: null
name: Description
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 38155520-fd68-4533-a707-ea49a31dcfcf # Standard
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
