columnSuffix: rzdnrsvd
contentColumnType: smallint(2)
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: duration
instructions: null
name: Duration
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 12
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: hours
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
