columnSuffix: kqxtuymw
contentColumnType: integer(10)
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: minLength
instructions: null
name: 'Min Length'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
