columnSuffix: null
contentColumnType: string
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: pageContent
instructions: null
name: 'Page Content'
searchable: true
settings:
  contentTable: '{{%matrixcontent_pagecontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
