columnSuffix: yhbuomkw
contentColumnType: integer(10)
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: price
instructions: null
name: Price
searchable: false
settings:
  currency: CAD
  defaultValue: null
  max: null
  min: 0
  showCurrency: true
  size: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Money
