columnSuffix: uuvcrylb
contentColumnType: datetime
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: startDate
instructions: null
name: 'Start Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 15
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
