columnSuffix: ebehctsr
contentColumnType: string(32)
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: startTime
instructions: null
name: 'Start Time'
searchable: false
settings:
  byteLimit: null
  charLimit: 8
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: '12:45 PM'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
