columnSuffix: owbnwclv
contentColumnType: string
fieldGroup: c0741afd-8d6d-4d7f-8380-02052e0593bf # Common
handle: testDropdown
instructions: null
name: 'Test Dropdown'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Thing A'
        -
          - value
          - thingA
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Thing B'
        -
          - value
          - thingB
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Thing C'
        -
          - value
          - thingC
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
