defaultPlacement: end
enableVersioning: true
handle: events
name: Events
propagationMethod: all
siteSettings:
  5dbfd761-5d6a-49ea-a0e9-e866c1c88e0f: # Ice & Dice
    enabledByDefault: true
    hasUrls: true
    template: entries/_event.twig
    uriFormat: 'events/{slug}'
type: channel
